### ISSUE TITLE
Pdf motion export: Missing meta data (referring motions)

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2642]
**Description:** The pdf motion export lacks in a specific meta data - "Referring motions". Also missing in the pdf output dialog menu is a button to turn this information on and off. The current workaround is to enter the referring applications in the application recommendation. This should not be the case.

**Example of meta data:**
![Screenshot_20230815_145025](https://github.com/OpenSlides/openslides-client/assets/105491030/573ee347-a140-429d-ad8f-b8560e109d52)

**Example of pdf export with missing meta information:**
![Screenshot_20230815_145159](https://github.com/OpenSlides/openslides-client/assets/105491030/208ae160-e071-48fe-9b9b-c78af067f0ac)

**Reproduction:**
1. open a meeting
2. open motions > create two motions with complex workflow
3. open workflows menu > activate in state for example zugelassen "Show recommendation extension field"
4. open settings > motions > add "ABK" in name of recommender field
5. open motions > open one motion > change recommendation to the state with an extension field and link the other motion. Now a reference should appear in the recommendation.
6. open the linked motion. In the meta data the referrenced motion should appear. > now export the pdf file

**What should happen:**

**Necessary:**
- [ ] 1. The referrenced data should be included in the standard single motion pdf export in the meta data.
- [ ] 2. Pdf export via multi selection in motions: The pdf dialog field should have a new button named "referrenced motions". So the user have the possibility to activate/deactivate the content

**Nice to have:**
- [ ] 3. The pdf motion dialog field should have no Scrollbar. It would be great to integrate a line break to see all boxes without scrolling.

**Comment by emanuelschuetze** [comment]
done in #2647
