### ISSUE TITLE
[META] Account Import issues

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2894]
**Description:** The account import has some issues, which needs to be fixed:

A) The preview doesn't include the vote weight value. This only affects the preview, not the actual import. The data will be correctly imported. It is only not displayed in the preview. 

B) If the Account import file has values which leads to warnings in the import preview, the warning message needs to be improved to focus more on the fact what actually happens. - The text part "Accounts with warnings (will be skipped)" indicates a skipping of the whole account during import. This is simply not true. Only the coloumn is excluded.

C) If a warning happens, a warning sign is displayed in the preview. The warning sign is quite generic for the warning in the password coloumn if the data also includes a SAML value. - Good would be a warning, which reflects the case. Here, that it is not possible to provide a password with a SAML value. - If this could be improved, it would be good. 

D) In the import description is a small ?-sign which could be clicked to get more information. This info-box should be improved for gender options. So the user can easily see, what could be used for import. 

**Reproduction:**

Case A) 
1. open the organiszation level
2. open Accounts
3. Import a user with a vote weight and check the preview of the data

Case B and C
1. Do an import of user data with username AND SAML until preview appears. In the preview box the text part "Accounts with warnings (will be skipped)" should appear. Also a warning sign should be visible in the username coloumn. Hover over it to see the warning message.

Case D)
1. Open Account > Import. Description is visible above.

**What should happen:**
- [x] A) The vote weight values should be included in the preview. 
- [x] B) Change text part to Accounts with warnings (Coloumns will be skipped)
- [x] C) Check of the warning message could be improved for this case or if it's a generic one for all coloumns. If it could be improved change it to "Import with SAML doesn't allow password."
- [x] D) Add all possible gender options to the help-box. This includes: female, male, diverse, non-binary

**Comment by reiterl** [comment]
Not a "good first issue". The decimal type seems to be missing and the account import dialog seems to have some more flaws (e.g. no username displayed).
