### ISSUE TITLE
[Meta] Superadmin problems in user profil menu

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#2917]
**Description:** The superadmin user profile has some issues.

- [x] Meeting list: The page My Meetings is empty and by opening it, an error appears multiple times in the console. (error TypeError: Cannot read properties of null (reading 'name') )
- [x] Present chock box is not available in some meetings. Reason and reproduction is unclear. (Could be found on our test instance in meeting 150) - Update 2023-10-20 Present box seems to work again. Still unclear, why it didn't worked 

**Reproduction:**
1. log in as superadmin
2. generate a meeting and add yourself to it
3. open the meeting
4. open the profile page and check My Meetings

**What should happen:**
- [x] Alle meetings should appear in My Meetings
- [x] The present check box should always be available

**Comment by MSoeb** [comment]
Issue will be closed. Worked now as it should. It seems to be solved by another unclear fix.
