### ISSUE TITLE
[Meta] Motion-detail view, visibility for motion.can_manage

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3147]
**Current behaviour:**
1.  the "Reset state" button is visible even if people do not have the permission to use it (if submitter are allowed to edit it/change the state, then they can see it)
2. create date is visible for everyone
3. creation date is above submission date

**Reproduction of 1.**
1. navigate to settings -> motion -> set "Workflow of new motions" to complex 
2. navigate to participants -> groups -> allow delegates to create new motions
3. navigate to motions -> workflows -> complex workflow -> activate "Allow submitter edit" for "in Bearbeitung"
4. login as a delegate
5. create a new motion, you are allowed to change the state and you can see the "reset state button"
6. if you press it the following error is thrown: 
```
Error: You are not allowed to perform action motion.reset_state. Missing Permission: motion.can_manage_metadata
```

**Wanted behaviour:**
- [x] the "Reset state button" and the mat-divider above it should only be visible if the operator can manage metadata
- [x] the creation date should only be visible if the operator if the operator can manage metadata
- [x] the submission date and the creation date should switch places

**Comment by reiterl** [comment]
Add a divider with the permission conditional above "Reset state".
