### ISSUE TITLE
[Meta] Two UI- change requests/bugs in los-extension

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3166]
- [x]  in a LoS the participant is currently displayed as "name ( number) structure level"
  - [x]  1.  The wanted display should be "name (structure level middot number)"
  - [x]  2. the text color should be the like the name and the font-style should be the same
 (see main as reference) 

- [x] the interposed question:
  - [x]  1. should not be bold 
  - [ ]  2. "Select or search new speaker" should be in box brackets

- [ ] The speaking time card: the color line and the structure level name should be aligned right
- [ ] in the autopilot:
  - [ ] 1. there should be a max-distance 75px between the left side of mat-cards and the right side (speaking times)
  - [ ] 2. if mobile view is activated then the speaking time card should jump directly under the LoS
