### ISSUE TITLE
[Meta] Design from speaking-times.component.html

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3198]
#3166 -> the not finished tasks are moved to this issue

- [x] The speaking time card:
   - [x] the color line, the countdown and the structure level name should be aligned right 
   - [x] the color line should be an element of it's own (maybe hline) and as long as the whole row minus the icon
   - [x] the more_vert icon should be right aligned
   - [x] the countdown should be in mono-font

- [x] in the autopilot:
  - [x] 1. there should be a max-distance 75px between the left side of mat-cards and the right side (speaking times)
  - [x] 2. #3196

**Comment by rrenkert** [comment]
![signal-2024-01-25-15-21-43-672.jpg](https://github.com/OpenSlides/openslides-client/assets/19685715/f6f753d3-1991-41f3-a186-76b0194582ba)

**Comment by Elblinator** [comment]
in the picture the line is a bit too fear right, it should stop before the more_vert menu
