### ISSUE TITLE
[Meta] New behaviours for LoS and if participants are on there several times

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3334]
**Currently:**
A new feature allows that one participant can be on a Los several times. The participant is only allowed to put themselves on the LoS once. Only a person with LoS_canmanage can put a participant on the list several times.
Now the LoS needs (potential) more visible information for the user: 

- [ ] the user/admin needs a marker to see which contribution was set by themselves use vs a different user
   - [ ] Question: should the marker (contribution is set by self) determined by the person who sets the contribution or should is be determined whether or not the contribution was added via the 'Add me' button we 'select the speaker box
   - [ ] The backend probably needs a new field which saves who/where/how/new boolean etc. the contribution was saved

- [ ] We need to discuss:
   - how the marker should look
   - if the marker should only be visible for contributions which were set by self/others

- [ ] Wanted behaviour?: A participant should always be able to put themselves on the list once and to ONLY remove themselves from the list if they put themselves on there
  - does this need a new setting?

**Summary:**
- add a marker for a contribution (self/other)
- design/UI/UX
- new setting, and new possibilities for the participant

**Comment by MSoeb** [comment]
Note: @emanuelschuetze - I've marked you for discussing purpose. We need to talk about this on a conceptual level, before coding can happen.

**Comment by MSoeb** [comment]
Currently there is no need to find a solution for this issue. At the moment this is only relevant and usable in parliament mode, in which the list of speakers is fully adminstrated and mostly pre-structured by the meeting administrators. As long delegates do not use the list of speakers buttons on their own, there is no need to change this. 

Nevertheless this issue should stay open, because we will need to improve this feature to made it usable for delegates in the future.
