### ISSUE TITLE
[META] Import Pages - Participants and Accounts

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#3809]
**Description:** 
The account and participant import pages need a rework. In its current state, the import user interface has several weaknesses which need to be improved. This issue is a META issue. It splits the work in small pieces to make it more manageable.

The following adjustments always apply to the participant import page. If the account page needs to be adjusted, there will be a note in the listed issues.

Note: This issue will be filled with more content. 

Current Issues:

- [x] https://github.com/OpenSlides/openslides-client/issues/3719
- [ ] https://github.com/OpenSlides/openslides-client/issues/3822
- [x] https://github.com/OpenSlides/openslides-client/issues/3823
- backend -><s>https://github.com/OpenSlides/openslides-backend/issues/2456</s>
