### ISSUE TITLE
Motion > amendment: formatting change in amendment plus original text leads to wrong diff

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4452]
**Describe the bug**
Part I: If an amendment change also includes a formatting change in amendment and original text, the diff will be wrong displayed. The whole paragraph will be shown as diff not the relevant parts.

Part II: If a motion paragraph includes for example a bold format in two sentences and an amendment is created in the second sentence with an additional word and a change in the bold content, than the diff is wrong displayed. The whole paragraph will be shown as diff. 

**Part I - Original motion:**
![image](https://github.com/user-attachments/assets/791685fd-657f-4cc8-8355-630c13ed969f)

**Part I - Amendment with red marked diff (amendment plus original text):**
![image](https://github.com/user-attachments/assets/ed543daf-1ff7-4b3e-878f-564628a93b1a)

**Part I - Outcome view:**
![image](https://github.com/user-attachments/assets/9d18a7bf-bbfe-4769-b3b9-1d205656814d)

**Part II - Original motion paragraph**
![image](https://github.com/user-attachments/assets/98d2492c-a3bf-47b5-a857-41ce35c98fc7)

**Part II - changes done in the amendment - changes are red marked:**
![image](https://github.com/user-attachments/assets/ea9deec8-8034-4631-bb98-711096407b8d)

**Part II - Outcome:**
![image](https://github.com/user-attachments/assets/2381e437-8e1f-417d-8060-7f3ac02cb2c7)

**How to Reproduce**
1. open a meeting
2. open motions > create a motion with two paragraphs. Add in the second paragraph a bold formatting of one word in the first and in the second sentence. > save it.
3. Part I - create an amendment in first paragraph and change one word. mark the new word and an original word in bold. > save diff
4. Part I - visual should now be broken like in the example above
5. Part II - create an amendment in second paragraph and change the second sentence as follow: add one new word right before the bold word and add content to the bold word > save diff

**Expected behavior**
If an amendment contains text and fomat changes, the diff visual should clearly display differences and should not show a change in the whole paragraph.

Important: Bold format is just an example. This problem also occurs for italic, underlined, strikethrough and color changes. This should not happen for all of these format changes. - FYI: I've tested all of this format types with Part I. At least for this, same problems occur.

This issue is part of the Meta Diff issue. #2956

**Comment by MSoeb** [comment]
- [ ] changed title
- [ ] extended problems with the counterpart of formatting
- [ ] added a new examples
- [ ] changed the expected behavior with additional requirements

**Comment by CatoTH** [comment]
https://github.com/OpenSlides/openslides-client/pull/4461
As mentioned in the PR, this does not fix all possible scenarios, but some relatively easy ones, including the first mentioned one here.

**Comment by Elblinator** [comment]
Part of this Issue was fixed and approved 
I' ll remove the staging label for now

**Comment by CatoTH** [comment]
Hi! I hope this fixes some of the remaining issues? https://github.com/OpenSlides/openslides-client/pull/4479

**Comment by Elblinator** [comment]
**Motion source code:**
```
<p>Jemand musste Josef K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines Morgens verhaftet. »Wie ein Hund! « sagte er, es war, als sollte die Scham ihn überleben.Als Gregor Samsa eines Morgens aus unruhigen Träumen erwachte, fand er sich in seinem Bett zu einem ungeheueren Ungeziefer verwandelt.</p>
<p>Und es war ihnen wie eine <strong>Bestätigung</strong> ihrer neuen Träume und guten Absichten, als am Ziele ihrer Fahrt die Tochter als erste sich erhob und ihren jungen <strong>Körper</strong> dehnte. motion with two paragraphs. Add in the second paragraph a bold formatting of one word in the first and in the second senence.</p>
```

**Amendments source code:**
Amendment changes line 5-8
```
<p>Und es war ihnen wie eine <strong>Bestätigung</strong> ihrer neuen Träume und guten Absichten, als am Ziele ihrer Fahrt die Tochter als erste sich erhob und ihren jungen alten <strong>Körpergehülle</strong> dehnte. motion with two paragraphs. Add in the second paragraph a bold formatting of one word in the first and in the second senence.</p>
```

**Comment by CatoTH** [comment]
It might well be that while trying to replicate the issue, I stumbled over another one. This isolated HTML snippet here definitively helps. One more attempt in the updated MR.

**Comment by MSoeb** [comment]
Found other formatting combinations for Part I which needs to fixed:
- Bold + Italic, Bold + underlined, Bold + strikethrough, Bold + Italic + underlined, Bold + Italic + strikethrough, Bold+italic+underlined+strikethrough, Italic + underlined, italic + strikethrough, italic + underlined + strike, underlied + strikethrough, 
- all combinations with text or background color

**Comment by Elblinator** [comment]
I'll close the issue here to refocus 

That is the new Issue for the fix persistent bugs https://github.com/OpenSlides/openslides-client/issues/4755
