### ISSUE TITLE
Roadmap CW 05

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#792]
Monday:
- [x] After creating an assignment, activating "global_abstain" throws an error
- [x] Deleting an assignment_poll throws an error
- [ ] #796
- [x] Cannot filter by open TOPs in an agenda

Tuesday:
- [ ] #798
- [x] Filtering in an agenda does not work
- [x] Filtering in a motion-list does not work
- [ ] #797

Wednesday:
- [x] Delegates can create a new user (if adding an assignment_candidate)
- [x] One cannot add an attachment to a TOP (with permission `agenda.can_manage`) (OpenSlides/openslides-autoupdate-service#409)
- [ ] Voting counter jumps to `0` if a user gets present within a meeting (OpenSlides/openslides-autoupdate-service#410)
- [x] After cloning a meeting, the recommendations' order does not match the order in the original meeting
- [ ] After cloning a meeting, the groups' order does not match the order in the original meeting (OpenSlides/openslides-backend#1189)
- [x] In a cloned meeting, the first group is not selectable in the user-list. However, the default group is selectable.
- [x] Error by calling `getGlobalNoClass`
